# Generated by Django 5.0.6 on 2024-05-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_doctors_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='department_name',
            new_name='dept_name',
        ),
    ]
