# Generated by Django 5.0.6 on 2024-05-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_rename_department_name_doctors_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dept_name',
            new_name='department_name',
        ),
    ]
