# Generated by Django 5.0.6 on 2024-06-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='TodoTitle')),
                ('description', models.TextField(max_length=300, verbose_name='description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='TodoCreateDate')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
