# Generated by Django 5.0.6 on 2024-06-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
    ]
