# Generated by Django 5.0.6 on 2024-06-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=200)),
                ('med_image', models.ImageField(default='default_image.jpg', upload_to='medicine')),
            ],
        ),
    ]
