# Generated by Django 5.0.6 on 2024-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='med_amount',
            field=models.IntegerField(default=0, verbose_name='M.R.P'),
        ),
    ]
