# Generated by Django 5.0.6 on 2024-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_pharmacy_med_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='med_amount',
            field=models.IntegerField(),
        ),
    ]
