# Generated by Django 5.0.6 on 2024-07-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_musicians_instrument_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='first_name',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='album',
        ),
        migrations.DeleteModel(
            name='musicians',
        ),
    ]
